/**
 * The Artwork view: drop a picture of a part in, then click its pins onto it.
 *
 * This is the GUI half of `specs/depictions.md` — the half that means nobody
 * has to hand-edit a `meta.json` or run a CLI to get real board pictures into
 * the schematic. Four things it is built around:
 *
 * 1. **Upload is a conversation, not a dialog box.** The host runs the import
 *    ladder's normalisation and hands back either what it changed ("emptied 12
 *    area fills — the house style is line art") or a refusal that names the
 *    rung the file is on and the one command that gets it onto a rung the tool
 *    supports. Both are shown verbatim: that paragraph *is* the feature.
 * 2. **Anchoring is click-a-pin, click-the-picture.** The terminal list is a
 *    checklist that arms the next unanchored pin for you, so a 21-pin connector
 *    is 21 clicks. An anchor that is slightly off is dragged, not retyped.
 * 3. **The mirror is shown, not explained.** The solder side sits beside the
 *    face view, updating live from the anchors being placed, labelled as
 *    generated. The rule the spec cares most about is the one the user watches
 *    happen.
 * 4. **What you just saved is what the schematic draws.** After a successful
 *    write the pane pulls the fresh manifest and bytes back and hands them
 *    upward as an overlay, so the preview redraws without a reload.
 *
 * No URL, no `fetch` and no file path appears here: the host supplies an
 * `ArtworkAdapter`, exactly as it supplies a `PersistenceAdapter`.
 */

import type { ConnectorBody, ConnectorDefinition, Db, Issue } from '@wirehub/model';
import type { DepictionArtwork } from '@wirehub/render-svg';
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type DragEvent,
  type JSX,
  type ReactNode,
  type PointerEvent as ReactPointerEvent,
  type WheelEvent as ReactWheelEvent,
} from 'react';

import { classes } from '../context.ts';
import type { AssetsAdapter, SharedAsset } from '../assets.ts';
import {
  isGerberBoard,
  padsOnSide,
  partsOnSide,
  type Pad as BoardPad,
} from '../board-art.ts';
import { BoardParts } from '../nodes/BoardNode.tsx';
import {
  boardOutlineFromSvg,
  defaultEntryGuides,
  extendGuideTo,
  guideSlots,
  offsetGuideTo,
} from '@wirehub/render-svg';
import { AssetPicker } from './AssetPicker.tsx';
import { BuiltInConnectorArt, builtInConnectorArt, drawnTerminals } from './BuiltInArt.tsx';
import {
  EMPTY_OVERLAY,
  IDENTITY_VIEW,
  anchorAt,
  anchorProgress,
  anchorsDiffer,
  armTerminal,
  beginAnchoring,
  clearAnchor,
  derivedAnchors,
  endDrag,
  isAnchored,
  mirrorCounterpart,
  moveAnchor,
  nextUnanchored,
  overlayWith,
  panBy,
  placeArmed,
  placement,
  startDrag,
  toStage,
  unanchoredSentence,
  zoomAbout,
  type AnchoringState,
  type ArtworkAdapter,
  type ArtworkDetail,
  type ArtworkOverlay,
  type ArtworkTerminal,
  type ArtworkView,
  type DepictionMeta,
  type EntryGuide,
  type Frame,
  type PinAnchor,
  type Stage,
  type UploadReport,
  type ViewTransform,
  type XY,
} from '../artwork.ts';

/* ------------------------------------------------------------------ *
 * Words
 * ------------------------------------------------------------------ */

/** What each view kind *is*, for someone who has never met the vocabulary. */
const VIEW_BLURB: Readonly<Record<string, string>> = {
  'schematic-symbol': 'The abstract symbol — how the part is drawn on a diagram, not how it looks.',
  'mating-face': 'The face you plug into, seen head-on. This is the one you anchor pins on.',
  'solder-side': 'The back of the connector, where you actually solder. Generated by flipping the face over.',
  'board-top': 'The component side of the board, seen from above. Anchor pads on this one.',
  'board-bottom': 'The underside of the board. Generated by flipping the top over.',
  illustration: 'A picture of the part for a build sheet — not something pins are anchored to.',
};

const VIEW_LABEL: Readonly<Record<string, string>> = {
  'schematic-symbol': 'Schematic symbol',
  'mating-face': 'Mating face',
  'solder-side': 'Solder side',
  'board-top': 'Board top',
  'board-bottom': 'Board bottom',
  illustration: 'Illustration',
};

function viewLabel(view: string): string {
  return VIEW_LABEL[view] ?? view;
}

/* ------------------------------------------------------------------ *
 * Small shared pieces
 * ------------------------------------------------------------------ */

function Problem(props: {
  message: string;
  hint?: string;
  issues?: Issue[];
  guidance?: string[];
  onDismiss?: () => void;
}): JSX.Element {
  return (
    <div className="cs-problem" role="alert">
      <strong>{props.message}</strong>
      {props.hint === undefined ? null : <span className="cs-problem-hint">{props.hint}</span>}
      {props.guidance === undefined || props.guidance.length === 0 ? null : (
        // shown exactly as the importer wrote it: the ladder's advice is the
        // product of a refusal, and paraphrasing it would lose the command
        <pre className="cs-artwork-guidance">{props.guidance.join('\n')}</pre>
      )}
      {props.issues === undefined || props.issues.length === 0 ? null : (
        <ul className="cs-problem-list">
          {props.issues.map((issue, index) => (
            <li key={`${issue.code}-${index}`}>{issue.message}</li>
          ))}
        </ul>
      )}
      {props.onDismiss === undefined ? null : (
        <button type="button" onClick={props.onDismiss}>
          dismiss
        </button>
      )}
    </div>
  );
}

/** The `<img>` src for one asset, self-contained either way. */
export function artworkSrc(art: DepictionArtwork | undefined): string | undefined {
  if (art === undefined) return undefined;
  if (art.kind === 'raster') return art.dataUri;
  if (art.source === undefined) return undefined;
  // an <img> cannot run script, so an SVG data URI is the safe way to show
  // artwork the editor did not author
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(art.source)}`;
}

/** A frame out of anything that carries `widthUnits`/`heightUnits` — an
 * `ArtworkView` (the detail's own shape) or a `DepictionMeta` asset entry
 * (the gerber display reads straight off `meta.views`). */
function frameOf(view: { widthUnits?: number; heightUnits?: number } | undefined): Frame | undefined {
  if (view?.widthUnits === undefined || view.heightUnits === undefined) return undefined;
  return { widthUnits: view.widthUnits, heightUnits: view.heightUnits };
}

/* ------------------------------------------------------------------ *
 * Upload
 * ------------------------------------------------------------------ */

interface UploadBoxProps {
  defId: string;
  view: string;
  existing?: ArtworkView;
  adapter: ArtworkAdapter;
  onUploaded: (report: UploadReport) => void;
  /** the shared asset library — "or pick one you already have" (50a.36) */
  assets?: AssetsAdapter;
}

/** What an upload accepts, said once — the drop zone's and the button's tooltip. */
export const ARTWORK_FORMATS_HELP =
  'PNG or SVG (JPEG accepted) · transparent background recommended · an SVG keeps its own millimetres, a picture needs its real width';

/** A picked shared asset, as the `File` an upload expects. */
async function fileOfAsset(asset: SharedAsset): Promise<File> {
  const blob = await (await fetch(asset.dataUri)).blob();
  return new File([blob], asset.originalName, { type: asset.mime });
}

function UploadBox(props: UploadBoxProps): JSX.Element {
  const [over, setOver] = useState(false);
  const [busy, setBusy] = useState(false);
  const [widthMm, setWidthMm] = useState('');
  const [src, setSrc] = useState('');
  const [report, setReport] = useState<UploadReport | undefined>(undefined);
  const [problem, setProblem] = useState<
    { message: string; hint?: string; guidance?: string[]; issues?: Issue[] } | undefined
  >(undefined);
  /** a file chosen while `existing` is already set — 50a.23: replacing what
   * is there is a decision, not a side effect of dropping a file */
  const [pendingFile, setPendingFile] = useState<File | undefined>(undefined);
  const [picking, setPicking] = useState(false);
  const input = useRef<HTMLInputElement>(null);

  const send = useCallback(
    async (file: File): Promise<void> => {
      setBusy(true);
      setProblem(undefined);
      setReport(undefined);
      const width = widthMm.trim() === '' ? undefined : Number(widthMm);
      const result = await props.adapter.upload(props.defId, props.view, {
        file: { name: file.name, blob: file },
        ...(width === undefined || !Number.isFinite(width) || width <= 0 ? {} : { widthMm: width }),
        ...(src.trim() === '' ? {} : { src: src.trim() }),
      });
      setBusy(false);
      if (result.ok) {
        setReport(result.value);
        props.onUploaded(result.value);
        return;
      }
      setProblem({
        message: result.message,
        ...(result.hint === undefined ? {} : { hint: result.hint }),
        ...(result.guidance === undefined ? {} : { guidance: result.guidance }),
        ...(result.issues === undefined ? {} : { issues: result.issues }),
      });
    },
    [props, widthMm, src],
  );

  /** A file was chosen (drop or picker). An empty view sends it straight
   * away; a view that already has a picture asks first — a silent overwrite
   * is exactly what 50a.23 is about. */
  const choose = (file: File): void => {
    if (props.existing !== undefined) {
      setPendingFile(file);
      return;
    }
    void send(file);
  };

  const onDrop = (event: DragEvent<HTMLDivElement>): void => {
    event.preventDefault();
    setOver(false);
    const file = event.dataTransfer.files[0];
    if (file !== undefined) choose(file);
  };

  return (
    <div className="cs-artwork-upload">
      <div className="cs-artwork-upload-head">
        <strong title={VIEW_BLURB[props.view] ?? ''}>{viewLabel(props.view)}</strong>
        {props.existing === undefined ? (
          <span className="cs-chip">nothing yet</span>
        ) : (
          <span className="cs-chip">
            {props.existing.file} · {props.existing.widthUnits} × {props.existing.heightUnits}{' '}
            {props.existing.kind === 'vector' ? 'mm' : 'px'}
          </span>
        )}
      </div>
      <div
        className={classes('cs-artwork-drop', over && 'is-over', busy && 'is-busy')}
        title={ARTWORK_FORMATS_HELP}
        onDragOver={(event) => {
          event.preventDefault();
          setOver(true);
        }}
        onDragLeave={() => setOver(false)}
        onDrop={onDrop}
      >
        <span>{busy ? 'importing…' : 'Drop PNG / SVG'}</span>
        <button type="button" disabled={busy} title={ARTWORK_FORMATS_HELP} onClick={() => input.current?.click()}>
          choose a file
        </button>
        {props.assets === undefined ? null : (
          <button type="button" disabled={busy} title="Reuse a picture already uploaded elsewhere" onClick={() => setPicking(true)}>
            pick existing
          </button>
        )}
        <input
          ref={input}
          type="file"
          accept=".svg,.png,.jpg,.jpeg,image/svg+xml,image/png,image/jpeg"
          aria-label={`artwork file for ${viewLabel(props.view)}`}
          onChange={(event) => {
            const file = event.target.files?.[0];
            event.target.value = '';
            if (file !== undefined) choose(file);
          }}
        />
      </div>

      <label
        className="cs-field"
        title="A photo or scan carries no scale of its own. An SVG usually does — leave empty to use its own millimetres."
      >
        <span>Real width (mm)</span>
        <input
          className="cs-input"
          value={widthMm}
          inputMode="decimal"
          placeholder="e.g. 54.5"
          onChange={(event) => setWidthMm(event.target.value)}
        />
      </label>
      <label className="cs-field" title="Provenance travels with the artwork. Left empty, the file name is all anyone gets.">
        <span>Source</span>
        <input
          className="cs-input"
          value={src}
          placeholder="datasheet p.3 · calipers · drawn by hand"
          onChange={(event) => setSrc(event.target.value)}
        />
      </label>

      {picking && props.assets !== undefined ? (
        <AssetPicker
          assets={props.assets}
          title={`Pick artwork for ${viewLabel(props.view)}`}
          onClose={() => setPicking(false)}
          onPick={(asset) => {
            setPicking(false);
            void fileOfAsset(asset).then(choose);
          }}
        />
      ) : null}

      {problem === undefined ? null : (
        <Problem {...problem} onDismiss={() => setProblem(undefined)} />
      )}
      {report === undefined ? null : (
        <div className="cs-artwork-report" role="status">
          <strong>
            Imported as {report.file} — {report.frame.widthUnits} × {report.frame.heightUnits}{' '}
            {report.kind === 'vector' ? 'mm' : `px at ${report.frame.mmPerUnit} mm/px`}.
          </strong>
          {report.warnings.length === 0 ? null : (
            <ul>
              {report.warnings.map((warning, index) => (
                <li key={index}>{warning}</li>
              ))}
            </ul>
          )}
        </div>
      )}

      {pendingFile === undefined ? null : (
        <div className="cs-modal" role="dialog" aria-modal="true" aria-label={`Replace ${viewLabel(props.view)} artwork`}>
          <div className="cs-modal-card">
            <h2>Replace this picture?</h2>
            <p className="cs-modal-say">
              This replaces <strong>{props.existing?.file}</strong> with <strong>{pendingFile.name}</strong>.
              The pins already placed on it stay exactly where they are — if the new picture is framed
              differently, they will no longer land on the right spots.
            </p>
            <div className="cs-modal-actions">
              <button type="button" className="cs-quiet" onClick={() => setPendingFile(undefined)}>
                Keep the current picture
              </button>
              <button
                type="button"
                className="cs-destructive"
                onClick={() => {
                  const file = pendingFile;
                  setPendingFile(undefined);
                  if (file !== undefined) void send(file);
                }}
              >
                Replace it
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * The anchoring stage
 * ------------------------------------------------------------------ */

interface StageProps {
  frame: Frame;
  art: DepictionArtwork | undefined;
  anchors: Record<string, PinAnchor>;
  /** ids drawn as "this is the one you are placing" */
  armed?: string;
  /** live means clicks place and drags move; a mirror preview is not live */
  live: boolean;
  /**
   * Draw the *picture* reversed. The anchors handed in are already reflected;
   * this is what makes the preview look like the other side rather than like
   * the same side with the pins jumbled.
   */
  flip?: 'x' | 'y';
  label: string;
  onPlace?: (point: XY) => void;
  onGrab?: (id: string) => void;
  onDragTo?: (point: XY) => void;
  onRelease?: () => void;
  dragging?: string;
  /**
   * Extra drawing over the picture (a board's mounted parts, 50a.38), built
   * for the picture's current on-screen scale — CSS px per frame unit — so
   * its text stays at screen size while it pans and zooms with the picture.
   */
  overlay?: (pxPerUnit: number) => ReactNode;
  /** clear air (px) kept round the fitted picture — room for a board's entry guides outside its edge */
  margin?: number;
}

/**
 * The picture, at whatever zoom and pan the user has it, with the anchors
 * drawn on top.
 *
 * Pan and zoom are hand-rolled — wheel to zoom about the cursor, drag the
 * background to pan — because the whole interaction is four lines of arithmetic
 * from `artwork.ts` and a library would be a dependency for nothing.
 */
function AnchorStage(props: StageProps): JSX.Element {
  const box = useRef<HTMLDivElement>(null);
  const [view, setView] = useState<ViewTransform>(IDENTITY_VIEW);
  const [stage, setStage] = useState<Stage>({ width: 0, height: 0 });
  const panning = useRef<XY | undefined>(undefined);

  useEffect(() => {
    const element = box.current;
    if (element === null) return;
    const measure = (): void =>
      setStage({ width: element.clientWidth, height: element.clientHeight });
    measure();
    if (typeof ResizeObserver === 'undefined') return;
    const observer = new ResizeObserver(measure);
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  const margin = props.margin ?? 0;
  const place = useMemo(() => {
    const fitted = placement(
      props.frame,
      { width: Math.max(0, stage.width - margin * 2), height: Math.max(0, stage.height - margin * 2) },
      view,
    );
    return { ...fitted, offsetX: fitted.offsetX + margin, offsetY: fitted.offsetY + margin };
  }, [props.frame, stage, view, margin]);
  const { overlay: buildOverlay } = props;
  const overlay = useMemo(
    () => (buildOverlay === undefined || place.scale <= 0 ? undefined : buildOverlay(place.scale)),
    [buildOverlay, place.scale],
  );

  const stagePoint = (event: ReactPointerEvent | ReactWheelEvent): XY => {
    const rect = box.current?.getBoundingClientRect();
    return {
      x: event.clientX - (rect?.left ?? 0),
      y: event.clientY - (rect?.top ?? 0),
    };
  };

  const onPointerDown = (event: ReactPointerEvent<HTMLDivElement>): void => {
    if (!props.live) return;
    const grabbed = (event.target as HTMLElement).dataset['anchorId'];
    if (grabbed !== undefined) {
      props.onGrab?.(grabbed);
      event.currentTarget.setPointerCapture(event.pointerId);
      return;
    }
    if (props.armed !== undefined) {
      props.onPlace?.(anchorAt(stagePoint(event), props.frame, place));
      return;
    }
    panning.current = stagePoint(event);
    event.currentTarget.setPointerCapture(event.pointerId);
  };

  const onPointerMove = (event: ReactPointerEvent<HTMLDivElement>): void => {
    const at = stagePoint(event);
    if (props.dragging !== undefined) {
      props.onDragTo?.(anchorAt(at, props.frame, place));
      return;
    }
    const from = panning.current;
    if (from === undefined) return;
    panning.current = at;
    setView((current) => panBy(current, at.x - from.x, at.y - from.y));
  };

  const onPointerUp = (): void => {
    panning.current = undefined;
    props.onRelease?.();
  };

  return (
    <div className="cs-artwork-stage-wrap">
      <div className="cs-artwork-stage-bar">
        <span>{props.label}</span>
        <span className="cs-spacer" />
        <button type="button" onClick={() => setView(IDENTITY_VIEW)}>
          fit
        </button>
        <span className="cs-chip">{Math.round(view.zoom * 100)}%</span>
      </div>
      <div
        ref={box}
        className={classes('cs-artwork-stage', props.live && props.armed !== undefined && 'is-placing')}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={onPointerUp}
        onWheel={(event) => {
          const factor = Math.exp(-event.deltaY / 400);
          setView((current) => zoomAbout(current, stagePoint(event), factor, props.frame, stage));
        }}
      >
        {artworkSrc(props.art) === undefined ? (
          <p className="cs-empty">no picture to show</p>
        ) : (
          <img
            className="cs-artwork-img"
            src={artworkSrc(props.art)}
            alt=""
            draggable={false}
            style={{
              position: 'absolute',
              left: `${place.offsetX}px`,
              top: `${place.offsetY}px`,
              width: `${props.frame.widthUnits * place.scale}px`,
              height: `${props.frame.heightUnits * place.scale}px`,
              ...(props.flip === undefined
                ? {}
                : { transform: props.flip === 'x' ? 'scaleX(-1)' : 'scaleY(-1)' }),
            }}
          />
        )}
        {overlay === undefined ? null : (
          <svg
            className="cs-artwork-overlay"
            viewBox={`0 0 ${props.frame.widthUnits * place.scale} ${props.frame.heightUnits * place.scale}`}
            style={{
              position: 'absolute',
              left: `${place.offsetX}px`,
              top: `${place.offsetY}px`,
              width: `${props.frame.widthUnits * place.scale}px`,
              height: `${props.frame.heightUnits * place.scale}px`,
            }}
          >
            {overlay}
          </svg>
        )}
        {Object.entries(props.anchors).map(([id, anchor]) => {
          const at = toStage(anchor, place);
          return (
            <span
              key={id}
              className={classes('cs-anchor-dot', props.armed === id && 'is-armed')}
              data-anchor-id={props.live ? id : undefined}
              title={`${id} — ${anchor.x}, ${anchor.y}`}
              style={{ left: `${at.x}px`, top: `${at.y}px` }}
            >
              <b data-anchor-id={props.live ? id : undefined} />
              <i>{id}</i>
            </span>
          );
        })}
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * Gerber boards: read-only, both faces side by side (3pn.4)
 * ------------------------------------------------------------------ */

/**
 * `board-top`/`board-bottom` pads, flattened to one dot per physical pad —
 * a terminal with more than one pad on a side (a GND spread across several)
 * gets a suffixed key so none collide.
 */
function padAnchorsOnSide(
  meta: DepictionMeta,
  side: 'top' | 'bottom',
  frame: Frame,
): Record<string, PinAnchor> {
  const out: Record<string, PinAnchor> = {};
  const pads = padsOnSide(meta, side, { width: frame.widthUnits, height: frame.heightUnits });
  for (const [terminal, list] of pads) {
    list.forEach(({ pad }: { pad: BoardPad; primary: boolean }, index: number) => {
      const key = list.length === 1 ? terminal : `${terminal}·${index}`;
      out[key] = { x: pad.x, y: pad.y };
    });
  }
  return out;
}

/** Where the default guide's `src` says it came from (a person then adjusts it). */
const DEFAULT_GUIDE_SRC =
  "Default (inferred): square to the row's pad approach axis, 1.5 mm outside the Edge.Cuts outline, 1.5 mm past the end pads — set in the Library guide editor.";

type GuideHandle = 'from' | 'to' | 'offset';

/**
 * One face's entry guides over its gerber art: the
 * guide, each pad's slot and straight lead, and three handles — the middle
 * one moves the guide square to itself (its offset from the edge; it stays
 * parallel to the row, square to the pads' approach axis), the end ones
 * slide its ends along it.
 */
function GuideOverlay(props: {
  meta: DepictionMeta;
  side: 'top' | 'bottom';
  guides: readonly EntryGuide[];
  width: number;
  pxPerUnit: number;
  editable: boolean;
  onChange: (index: number, guide: EntryGuide) => void;
}): JSX.Element {
  const { meta, side, guides, width, pxPerUnit, editable, onChange } = props;
  const drag = useRef<{ index: number; handle: GuideHandle } | undefined>(undefined);
  // anchor frame → this face's own picture (the bottom is mirrored about x)
  const px = (x: number, y: number): XY => ({ x: (side === 'top' ? x : width - x) * pxPerUnit, y: y * pxPerUnit });
  const toUnits = (event: ReactPointerEvent<SVGElement>): XY => {
    const svg = event.currentTarget.ownerSVGElement;
    const rect = svg?.getBoundingClientRect();
    const ux = (event.clientX - (rect?.left ?? 0)) / pxPerUnit;
    const uy = (event.clientY - (rect?.top ?? 0)) / pxPerUnit;
    return { x: side === 'top' ? ux : width - ux, y: uy };
  };
  return (
    <g className="cs-guides">
      {guides.map((guide, index) => {
        if (guide.side !== side) return null;
        const from = px(guide.from[0], guide.from[1]);
        const to = px(guide.to[0], guide.to[1]);
        const mid = { x: (from.x + to.x) / 2, y: (from.y + to.y) / 2 };
        const handle = (kind: GuideHandle, at: XY, title: string): JSX.Element => (
          <circle
            key={kind}
            className={classes('cs-guide-handle', kind === 'offset' && 'is-offset')}
            data-guide-handle={`${side}:${index}:${kind}`}
            cx={at.x}
            cy={at.y}
            r={kind === 'offset' ? 5.5 : 4.5}
            onPointerDown={(event) => {
              event.stopPropagation();
              drag.current = { index, handle: kind };
              event.currentTarget.setPointerCapture?.(event.pointerId);
            }}
            onPointerMove={(event) => {
              const active = drag.current;
              if (active === undefined || active.index !== index || active.handle !== kind) return;
              const point = toUnits(event);
              onChange(index, kind === 'offset' ? offsetGuideTo(guide, point) : extendGuideTo(guide, kind, point));
            }}
            onPointerUp={() => {
              drag.current = undefined;
            }}
          >
            <title>{title}</title>
          </circle>
        );
        return (
          <g key={index} className="cs-guide">
            {guideSlots(meta, guide).map((slot) => {
              const pad = px(slot.pad.x, slot.pad.y);
              const at = px(slot.slot.x, slot.slot.y);
              return (
                <g key={slot.ref} className={classes('cs-guide-slot', !slot.clear && 'is-blocked')}>
                  <line x1={pad.x} y1={pad.y} x2={at.x} y2={at.y} />
                  <circle cx={at.x} cy={at.y} r={2.2}>
                    <title>{`${slot.ref}${slot.straight ? '' : ' · aimed through the gap'}${slot.clear ? '' : ' · crosses a pad'}`}</title>
                  </circle>
                </g>
              );
            })}
            <line className="cs-guide-line" x1={from.x} y1={from.y} x2={to.x} y2={to.y}>
              <title>{`Entry guide · ${guide.pads.join(' ')} — ${guide.src}`}</title>
            </line>
            {editable ? (
              <>
                {handle('from', from, 'Drag to move this end along the guide')}
                {handle('to', to, 'Drag to move this end along the guide')}
                {handle('offset', mid, "Drag to set the guide's distance from the board edge — it stays parallel to the row")}
              </>
            ) : null}
          </g>
        );
      })}
    </g>
  );
}

function sameGuides(a: readonly EntryGuide[], b: readonly EntryGuide[]): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

/**
 * A gerber-sourced board's artwork: the production fabrication output
 * (`scripts/import-gerbers.ts`), not something anyone draws or anchors by
 * hand — the same reason the tool owns the solder-side mirror is why it owns
 * this. Reuses `board-art.ts`'s own pad-reflection helper (`padsOnSide`)
 * rather than re-deriving which pad lands on which face.
 *
 * The one hand-set thing on it: each angled pad row's **entry guide**
 *, drawn over the art and dragged into place; a face
 * with an angled row but no stored guide starts from the default.
 */
function GerberBoardArt(props: {
  meta: DepictionMeta;
  art: Record<string, DepictionArtwork>;
  onSaveGuides?: (guides: readonly EntryGuide[]) => Promise<string | undefined>;
}): JSX.Element {
  const { meta, art, onSaveGuides } = props;
  const top = meta.views['board-top'];
  const bottom = meta.views['board-bottom'];
  const topFrame = frameOf(top);
  const stored = useMemo(() => meta.entryGuides ?? [], [meta]);
  const topArt = art['board-top'];
  const defaults = useMemo(() => {
    const source = topArt?.kind === 'vector' ? topArt.source : undefined;
    return defaultEntryGuides(meta, source === undefined ? undefined : boardOutlineFromSvg(source), DEFAULT_GUIDE_SRC);
  }, [meta, topArt]);
  // stored guides win; a face with an angled row and none stored starts from its default
  const initial = useMemo(
    () => [...stored, ...defaults.filter((guide) => !stored.some((own) => own.side === guide.side))],
    [stored, defaults],
  );
  const [guides, setGuides] = useState<EntryGuide[]>(initial);
  const [saving, setSaving] = useState(false);
  const [problem, setProblem] = useState<string | undefined>(undefined);
  useEffect(() => setGuides(initial), [initial]);
  const dirty = !sameGuides(guides, stored);
  const change = useCallback((index: number, guide: EntryGuide): void => {
    setGuides((current) => current.map((own, at) => (at === index ? guide : own)));
  }, []);

  if (topFrame === undefined) {
    return <p className="cs-empty">This board's gerber artwork has no usable frame.</p>;
  }
  const bottomFrame = frameOf(bottom) ?? topFrame;
  const topAnchors = padAnchorsOnSide(meta, 'top', topFrame);
  const bottomAnchors = padAnchorsOnSide(meta, 'bottom', topFrame);
  // the build's mounted parts over each face — the same overlay the canvas
  // board node draws (y1u.17/18), unturned and at the canvas's own scale
  const hasParts = (side: 'top' | 'bottom'): boolean =>
    (meta.components?.parts ?? []).some((part) => part.side === side);
  const editable = onSaveGuides !== undefined;
  const hasGuides = guides.length > 0;
  const overlayFor =
    (side: 'top' | 'bottom') =>
    (pxPerUnit: number): ReactNode => (
      <>
        {hasParts(side) ? (
          <BoardParts
            parts={partsOnSide(meta, side, { width: topFrame.widthUnits, height: topFrame.heightUnits }, 0, pxPerUnit)}
            labels
          />
        ) : null}
        {hasGuides ? (
          <GuideOverlay
            meta={meta}
            side={side}
            guides={guides}
            width={topFrame.widthUnits}
            pxPerUnit={pxPerUnit}
            editable={editable}
            onChange={change}
          />
        ) : null}
      </>
    );
  const save = async (): Promise<void> => {
    if (onSaveGuides === undefined) return;
    setSaving(true);
    setProblem(await onSaveGuides(guides));
    setSaving(false);
  };
  const overlays = (side: 'top' | 'bottom'): { overlay?: (pxPerUnit: number) => ReactNode } =>
    hasParts(side) || hasGuides ? { overlay: overlayFor(side) } : {};

  return (
    <section className="cs-artwork-gerber">
      {hasGuides ? (
        <div className="cs-guide-bar">
          <span
            className={classes('cs-chip', !dirty && stored.length > 0 && 'is-done')}
            title="Entry guides: where wires to an angled pad row reach the board, before the straight lead in. Drag a guide's middle handle to set its distance from the edge, its end handles to set its length."
          >
            {guides.length} entry guide{guides.length === 1 ? '' : 's'}
            {dirty ? ' · unsaved' : ''}
          </span>
          <span className="cs-spacer" />
          {editable ? (
            <>
              <button
                type="button"
                disabled={sameGuides(guides, defaults)}
                title="Put every guide back to its default: square to the row, 1.5 mm outside the board edge"
                onClick={() => setGuides(defaults)}
              >
                default
              </button>
              <button type="button" disabled={!dirty} title="Undo the changes since the last save" onClick={() => setGuides(initial)}>
                revert
              </button>
              <button
                type="button"
                disabled={!dirty || saving}
                title="Write the guides into this board's reviewed kicad-map (and its manifest)"
                onClick={() => void save()}
              >
                {saving ? 'saving…' : 'save guides'}
              </button>
            </>
          ) : null}
        </div>
      ) : null}
      {problem === undefined ? null : <Problem message={problem} onDismiss={() => setProblem(undefined)} />}
      <div className="cs-artwork-stages">
        <AnchorStage
          frame={topFrame}
          art={art['board-top']}
          anchors={topAnchors}
          live={false}
          label="Board top"
          margin={hasGuides ? 40 : 0}
          {...overlays('top')}
        />
        <AnchorStage
          frame={bottomFrame}
          art={art['board-bottom']}
          anchors={bottomAnchors}
          live={false}
          label="Board bottom"
          margin={hasGuides ? 40 : 0}
          {...overlays('bottom')}
        />
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ *
 * The definition's artwork screen
 * ------------------------------------------------------------------ */

export interface DetailProps {
  defId: string;
  adapter: ArtworkAdapter;
  /**
   * The connector's own definition, when this is a connector: its built-in
   * drawing (`connector-art.ts`) is shown first, as what the builder uses,
   * and uploaded artwork becomes an optional extra (50a.38).
   */
  connector?: ConnectorDefinition;
  /** the body that connector is built on: the built-in drawing is the body's */
  body?: ConnectorBody;
  /** labels of every pinout on that body — they all share this drawing */
  sharedBy?: readonly string[];
  /** the shared asset library, for "pick existing" beside each upload */
  assets?: AssetsAdapter;
  onOverlay: (
    defId: string,
    detail: ArtworkDetail,
    assets: Record<string, DepictionArtwork>,
  ) => void;
}

export function ArtworkDetailPane(props: DetailProps): JSX.Element {
  const { defId, adapter, onOverlay } = props;
  const [detail, setDetail] = useState<ArtworkDetail | undefined>(undefined);
  const [art, setArt] = useState<Record<string, DepictionArtwork>>({});
  const [state, setState] = useState<AnchoringState>(() => beginAnchoring({}));
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<string | undefined>(undefined);
  const [problem, setProblem] = useState<
    { message: string; hint?: string; issues?: Issue[] } | undefined
  >(undefined);
  const [loadProblem, setLoadProblem] = useState<string | undefined>(undefined);

  /**
   * Re-read everything and hand it upward as an overlay.
   *
   * The bytes are fetched here rather than left to the host because *this* is
   * the moment the page learns about artwork its bundle never had: the studio's
   * `DepictionSource` was globbed at build time, and a file uploaded thirty
   * seconds ago is not in it. Pulling the manifest and the assets back after
   * every successful write is what lets the schematic redraw without a reload.
   */
  const refresh = useCallback(async (): Promise<void> => {
    const result = await adapter.detail(defId);
    if (!result.ok) {
      setLoadProblem(`${result.message} ${result.hint ?? ''}`.trim());
      setDetail(undefined);
      return;
    }
    setLoadProblem(undefined);
    setDetail(result.value);
    setState(beginAnchoring(result.value.pinAnchors));
    const assets: Record<string, DepictionArtwork> = {};
    for (const view of result.value.views) {
      const bytes = await adapter.artwork(defId, view.view);
      if (bytes.ok) assets[view.view] = bytes.value;
    }
    setArt(assets);
    onOverlay(defId, result.value, assets);
  }, [adapter, defId, onOverlay]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const definition = detail?.definition;
  const terminals: ArtworkTerminal[] = definition?.terminals ?? [];
  const progress = useMemo(() => anchorProgress(terminals, state.anchors), [terminals, state.anchors]);
  const missingSentence = unanchoredSentence(progress, definition?.label ?? defId, detail?.usedBy);
  /**
   * Gerber-sourced boards (`sourceKind: 'gerber'`) are the production
   * fabrication output, not a picture someone drew — regenerated by
   * `scripts/import-gerbers.ts`, never hand-uploaded or hand-anchored
   * (3pn.4). `isGerberBoard` is the same check the canvas uses to decide
   * whether to draw real board art.
   */
  const gerber = isGerberBoard(detail?.meta);

  const frameView = useMemo(() => {
    if (detail === undefined) return undefined;
    const named = detail.views.find((view) => view.view === detail.anchorFrame);
    return named ?? detail.views.find((view) => !view.derived);
  }, [detail]);
  const frame = frameOf(frameView);

  const mirrorName = frameView === undefined ? undefined : mirrorCounterpart(frameView.view);
  const mirrorAxis =
    (mirrorName === undefined
      ? undefined
      : detail?.views.find((view) => view.view === mirrorName)?.mirrorAxis) ?? 'x';
  const mirrored = useMemo(
    () => (frame === undefined ? {} : derivedAnchors(state.anchors, mirrorAxis, frame)),
    [state.anchors, mirrorAxis, frame],
  );

  const dirty = detail === undefined ? false : anchorsDiffer(state.anchors, detail.pinAnchors);

  /** the builder's own drawing of this connector, when its family has one */
  const builtIn = useMemo(() => builtInConnectorArt(props.connector, props.body), [props.connector, props.body]);
  /** anything uploaded that pins are placed on by hand */
  const manual = frameView !== undefined;
  const anchorChip = ((): { text: string; title: string; done: boolean } => {
    const total = terminals.length;
    if (gerber) {
      const placed = Math.max(0, total - (detail?.unanchored.length ?? 0));
      return {
        text: `${placed}/${total} anchored · derived`,
        title: 'Pad positions come from the production gerbers — nothing to place by hand.',
        done: placed === total,
      };
    }
    if (builtIn !== undefined && !manual && props.connector !== undefined) {
      const drawn = drawnTerminals(builtIn);
      // the definition itself is the authority on which pins there are
      const pins = props.connector.pins.map((pin) => pin.id);
      const placed = pins.filter((id) => drawn.has(id)).length;
      return {
        text: `${placed}/${pins.length} anchored · derived`,
        title: 'Pin positions come from the built-in drawing; only uploaded artwork needs pins placed by hand.',
        done: placed === pins.length,
      };
    }
    return {
      text: `${progress.anchored.length}/${total} anchored`,
      title: 'Pins placed by hand on the uploaded picture — click a pin, then its spot.',
      done: progress.complete,
    };
  })();

  const save = async (): Promise<void> => {
    if (detail === undefined || frameView === undefined) return;
    setSaving(true);
    setProblem(undefined);
    const result = await adapter.saveAnchors(defId, {
      anchorFrame: frameView.view,
      pinAnchors: state.anchors,
    });
    setSaving(false);
    if (!result.ok) {
      setProblem({
        message: result.message,
        ...(result.hint === undefined ? {} : { hint: result.hint }),
        ...(result.issues === undefined ? {} : { issues: result.issues }),
      });
      return;
    }
    setDetail(result.value);
    setState(beginAnchoring(result.value.pinAnchors));
    setNotice('Anchors saved. The schematic preview is already drawing them.');
    onOverlay(defId, result.value, art);
  };

  if (loadProblem !== undefined) {
    return (
      <div className="cs-artwork-detail">
        <Problem message="The studio could not read this definition's artwork." hint={loadProblem} />
      </div>
    );
  }
  if (detail === undefined) return <p className="cs-empty">loading…</p>;

  return (
    <div className="cs-artwork-detail">
      <header className="cs-artwork-head">
        <strong>{definition?.label ?? defId}</strong>
        <span className="cs-doc-id">{defId}</span>
        {definition === undefined ? (
          <span className="cs-chip is-error">not a definition this catalog knows</span>
        ) : (
          <span className="cs-chip">
            {definition.kind} · {terminals.length} terminal{terminals.length === 1 ? '' : 's'}
          </span>
        )}
        <span className="cs-spacer" />
        {gerber ? (
          <span
            className="cs-chip"
            title="This artwork is rendered from the production gerbers by scripts/import-gerbers.ts — not something to draw or anchor by hand. Regenerate it there if the board revision changed."
          >
            From gerbers — read-only
          </span>
        ) : null}
        <span className={classes('cs-chip', anchorChip.done && 'is-done')} title={anchorChip.title}>
          {anchorChip.text}
        </span>
      </header>

      {gerber && detail.meta !== undefined ? (
        <GerberBoardArt
          meta={detail.meta}
          art={art}
          {...(adapter.saveEntryGuides === undefined
            ? {}
            : {
                onSaveGuides: async (guides: readonly EntryGuide[]): Promise<string | undefined> => {
                  const result = await adapter.saveEntryGuides!(defId, guides);
                  if (!result.ok) return `${result.message} ${result.hint ?? ''}`.trim();
                  setDetail(result.value);
                  onOverlay(defId, result.value, art);
                  return undefined;
                },
              })}
        />
      ) : (
        <>
          {builtIn !== undefined && props.connector !== undefined ? (
            <BuiltInConnectorArt
              def={props.connector}
              art={builtIn}
              {...(props.body === undefined ? {} : { body: props.body })}
              {...(props.sharedBy === undefined ? {} : { sharedBy: props.sharedBy })}
            />
          ) : props.connector !== undefined ? (
            <p className="cs-empty" title="connector-art.ts has no drawing for this family">
              No built-in drawing for {props.connector.family ?? 'this family'} — the builder shows a pin list.
            </p>
          ) : null}
          <details className="cs-artwork-extra" open={builtIn === undefined || manual || detail.views.length > 0}>
            <summary title={`Optional: your own picture, shown alongside the built-in drawing. ${ARTWORK_FORMATS_HELP}.`}>
              Uploaded artwork <span className="cs-chip">{builtIn === undefined ? 'for pin anchors' : 'optional'}</span>
            </summary>
          <section className="cs-artwork-uploads">
            {detail.uploadableViews.map((view) => {
              const existing = detail.views.find((entry) => entry.view === view);
              return (
                <UploadBox
                  key={view}
                  defId={defId}
                  view={view}
                  adapter={adapter}
                  {...(existing === undefined ? {} : { existing })}
                  {...(props.assets === undefined ? {} : { assets: props.assets })}
                  onUploaded={() => void refresh()}
                />
              );
            })}
            <p
              className="cs-artwork-derived-note"
              title="Mirroring a pinout by eye is the classic wiring error, so this is one job the tool does not hand back to you."
            >
              Solder side / board underside: generated by flipping the face — never uploaded.
            </p>
          </section>

          {frameView === undefined || frame === undefined ? (
            <p className="cs-empty">
              Upload a picture above, and the pin list appears here for you to click onto it.
            </p>
          ) : (
            <section className="cs-artwork-anchoring">
          <div className="cs-artwork-checklist">
            <div className="cs-artwork-checklist-head">
              <strong title="Click a pin, then click where it sits on the picture. Drag a dot to nudge it. Scroll to zoom, drag the background to move around.">
                Pins
              </strong>
              <span className="cs-count">
                {progress.todo.length} to place
                {detail?.usedBy === undefined ? null : (
                  <span title="unplaced pins a cable solders to"> · {progress.todo.filter((id) => (detail.usedBy?.[id]?.length ?? 0) > 0).length} used</span>
                )}
              </span>
            </div>
            <ul className="cs-scroll cs-artwork-terminals">
              {terminals.map((terminal) => {
                const done = isAnchored(terminal, state.anchors);
                const usedBy = detail?.usedBy?.[terminal.id] ?? [];
                return (
                  <li key={terminal.id}>
                    <button
                      type="button"
                      {...(detail?.usedBy === undefined
                        ? {}
                        : { title: usedBy.length === 0 ? 'no cable solders here' : `soldered in ${usedBy.length === 1 ? usedBy[0] : `${usedBy.length} cables`}` })}
                      data-used={detail?.usedBy === undefined ? undefined : usedBy.length > 0}
                      className={classes(
                        'cs-artwork-terminal',
                        done && 'is-done',
                        state.armed === terminal.id && 'is-armed',
                      )}
                      aria-pressed={state.armed === terminal.id}
                      onClick={() => setState((current) => armTerminal(current, terminal.id))}
                    >
                      <span className="cs-artwork-tick">{done ? '✓' : '·'}</span>
                      <span className="cs-artwork-tid">{terminal.id}</span>
                      {terminal.label === undefined ? null : (
                        <span className="cs-artwork-tlabel">{terminal.label}</span>
                      )}
                    </button>
                    {done ? (
                      <button
                        type="button"
                        className="cs-artwork-clear"
                        title={`take ${terminal.id} off the picture`}
                        onClick={() => setState((current) => clearAnchor(current, terminal.id))}
                      >
                        ×
                      </button>
                    ) : null}
                  </li>
                );
              })}
            </ul>
            <div className="cs-artwork-actions">
              <button
                type="button"
                disabled={terminals.length === 0}
                onClick={() =>
                  setState((current) => {
                    const next = nextUnanchored(terminals, current.anchors);
                    return next === undefined ? current : armTerminal(current, next);
                  })
                }
              >
                arm the next one
              </button>
              <button type="button" disabled={!dirty || saving} onClick={() => void save()}>
                {saving ? 'saving…' : 'save anchors'}
              </button>
            </div>
            {missingSentence === undefined ? null : <p className="cs-doc-warning">{missingSentence}</p>}
            {progress.stray.length === 0 ? null : (
              <p className="cs-doc-warning">
                {progress.stray.join(', ')} {progress.stray.length === 1 ? 'is' : 'are'} anchored but
                no longer {progress.stray.length === 1 ? 'a terminal' : 'terminals'} of this part —
                saving will be refused until {progress.stray.length === 1 ? 'it is' : 'they are'}{' '}
                removed.
              </p>
            )}
            {problem === undefined ? null : (
              <Problem {...problem} onDismiss={() => setProblem(undefined)} />
            )}
            {notice === undefined ? null : (
              <p className="cs-artwork-notice" role="status">
                {notice}
              </p>
            )}
          </div>

          <div className="cs-artwork-stages">
            <AnchorStage
              frame={frame}
              art={art[frameView.view]}
              anchors={state.anchors}
              {...(state.armed === undefined ? {} : { armed: state.armed })}
              {...(state.dragging === undefined ? {} : { dragging: state.dragging })}
              live
              label={`${viewLabel(frameView.view)} — the one you anchor`}
              onPlace={(point) => {
                setNotice(undefined);
                setState((current) => placeArmed(current, point, terminals));
              }}
              onGrab={(id) => setState((current) => startDrag(current, id))}
              onDragTo={(point) =>
                setState((current) =>
                  current.dragging === undefined
                    ? current
                    : moveAnchor(current, current.dragging, point),
                )
              }
              onRelease={() => setState((current) => endDrag(current))}
            />
            <div className="cs-artwork-mirror">
              <AnchorStage
                frame={frame}
                art={art[frameView.view]}
                anchors={mirrored}
                live={false}
                flip={mirrorAxis}
                label={`${mirrorName === undefined ? 'The other side' : viewLabel(mirrorName)} — generated`}
              />
              <p
                className="cs-artwork-blurb"
                title={`Worked out from the anchors on the left by flipping them across the ${mirrorAxis === 'x' ? 'vertical' : 'horizontal'} centre line — you never enter it, and it updates as you place each pin.`}
              >
                Generated from the anchors on the left.
              </p>
            </div>
          </div>
            </section>
          )}
          </details>
        </>
      )}

      {detail.issues.length === 0 ? null : (
        <ul className="cs-scroll cs-artwork-issues">
          {detail.issues.map((issue, index) => (
            <li key={`${issue.code}-${index}`} className={classes('cs-issue', issue.severity === 'error' && 'is-error')}>
              <span className="cs-issue-code">{issue.code}</span>
              {issue.message}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * The tab
 * ------------------------------------------------------------------ */

export interface ArtworkProps {
  db: Db;
  adapter: ArtworkAdapter;
  /**
   * Artwork the page now knows about that its bundled source does not. The
   * host layers this over whatever it built at compile time, which is what
   * makes a just-uploaded picture show up in the schematic without a reload.
   */
  onOverlayChange?: (overlay: ArtworkOverlay) => void;
  /** the definition to open first — usually one the open design uses */
  initialDefId?: string;
}

/** Every definition a depiction can be attached to, in one searchable list. */
export function depictableDefinitions(
  db: Db,
): { id: string; label: string; kind: 'connector' | 'component' | 'pcba' }[] {
  return [
    ...db.connectors.map((c) => ({ id: c.id, label: c.label, kind: 'connector' as const })),
    ...db.pcbas.map((p) => ({ id: p.id, label: p.label, kind: 'pcba' as const })),
    ...db.components.map((c) => ({ id: c.id, label: c.label, kind: 'component' as const })),
  ];
}

export function ArtworkPane(props: ArtworkProps): JSX.Element {
  const entries = useMemo(() => depictableDefinitions(props.db), [props.db]);
  const [query, setQuery] = useState('');
  const [defId, setDefId] = useState<string | undefined>(
    () => props.initialDefId ?? entries[0]?.id,
  );
  const overlay = useRef<ArtworkOverlay>(EMPTY_OVERLAY);

  const { onOverlayChange } = props;
  const onOverlay = useCallback(
    (id: string, detail: ArtworkDetail, assets: Record<string, DepictionArtwork>): void => {
      if (detail.meta === undefined && Object.keys(assets).length === 0) return;
      overlay.current = overlayWith(overlay.current, id, detail.meta, assets);
      onOverlayChange?.(overlay.current);
    },
    [onOverlayChange],
  );

  const shown = useMemo(() => {
    const needle = query.trim().toLowerCase();
    if (needle === '') return entries;
    return entries.filter(
      (entry) =>
        entry.id.toLowerCase().includes(needle) || entry.label.toLowerCase().includes(needle),
    );
  }, [entries, query]);

  return (
    <div className="cs-artwork">
      <aside className="cs-artwork-picker">
        <input
          className="cs-input"
          value={query}
          placeholder="find a part"
          aria-label="find a part"
          onChange={(event) => setQuery(event.target.value)}
        />
        <ul className="cs-scroll">
          {shown.map((entry) => (
            <li key={`${entry.kind}-${entry.id}`}>
              <button
                type="button"
                className={classes('cs-artwork-pick', defId === entry.id && 'is-active')}
                aria-pressed={defId === entry.id}
                onClick={() => setDefId(entry.id)}
              >
                <span className="cs-part-label">{entry.label}</span>
                <span className="cs-part-detail">
                  {entry.kind} · {entry.id}
                </span>
              </button>
            </li>
          ))}
          {shown.length === 0 ? <li className="cs-empty">nothing matches “{query}”</li> : null}
        </ul>
      </aside>
      {defId === undefined ? (
        <p className="cs-empty">This catalog has no parts to draw yet.</p>
      ) : (
        <ArtworkDetailPane key={defId} defId={defId} adapter={props.adapter} onOverlay={onOverlay} />
      )}
    </div>
  );
}
