/**
 * Secrets entered in Settings (`specs/runtime-settings.md` §4): the SMTP
 * password, the OIDC client secret, the alert webhook's URL and token, the git
 * mirror's token and deploy key.
 *
 * They are never catalog documents — the catalog is exported, git-mirrored and
 * kept in the change history, and none of those may carry a secret. They live
 * in a store of their own (`studio.settings_secret` on Postgres, a file beside
 * the sign-in data on files), always as AES-256-GCM ciphertext under a key the
 * install provides (`WIREHUB_SETTINGS_KEY`, generated by the stack's bootstrap
 * into the `secrets` volume as `settings_key`). The API takes a secret and
 * answers only whether one is set; it never sends one back.
 *
 * A ciphertext is `v1.<iv>.<ciphertext>.<tag>` (base64url). The AES key is
 * derived from the install key with HKDF-SHA256, and the organisation and the
 * secret's name are its additional data, so a value copied to another row or
 * another organisation does not decrypt.
 */

import { createCipheriv, createDecipheriv, hkdfSync, randomBytes } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import type { Env } from './env.ts';

/** The shortest install key accepted (a generated one is 43 characters of base64url). */
export const MIN_SETTINGS_KEY_LENGTH = 32;

export class SettingsKeyError extends Error {}

/** `WIREHUB_SETTINGS_KEY` (or its `_FILE`, already resolved at boot), or `undefined` when unset. Throws when it is too short to be a key. */
export function settingsKeyFromEnv(env: Env): string | undefined {
  const key = (env['WIREHUB_SETTINGS_KEY'] ?? '').trim();
  if (key === '') return undefined;
  if (key.length < MIN_SETTINGS_KEY_LENGTH) throw new SettingsKeyError(`WIREHUB_SETTINGS_KEY must be at least ${MIN_SETTINGS_KEY_LENGTH} characters (generate one with \`openssl rand -base64 32\`).`);
  return key;
}

export interface SettingsCipher {
  encrypt(org: string, name: string, plaintext: string): string;
  /** the plain text, or `undefined` when it does not decrypt (another key, another org or name, damaged) */
  decrypt(org: string, name: string, ciphertext: string): string | undefined;
}

export function settingsCipher(installKey: string): SettingsCipher {
  const key = Buffer.from(hkdfSync('sha256', installKey, 'wirehub-settings-secrets', 'aes-256-gcm v1', 32));
  const aad = (org: string, name: string): Buffer => Buffer.from(`${org}\u0000${name}`, 'utf8');
  return {
    encrypt(org, name, plaintext) {
      const iv = randomBytes(12);
      const cipher = createCipheriv('aes-256-gcm', key, iv);
      cipher.setAAD(aad(org, name));
      const body = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
      return ['v1', iv.toString('base64url'), body.toString('base64url'), cipher.getAuthTag().toString('base64url')].join('.');
    },
    decrypt(org, name, ciphertext) {
      const [version, iv, body, tag, ...rest] = ciphertext.split('.');
      if (version !== 'v1' || iv === undefined || body === undefined || tag === undefined || rest.length > 0) return undefined;
      try {
        const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(iv, 'base64url'));
        decipher.setAAD(aad(org, name));
        decipher.setAuthTag(Buffer.from(tag, 'base64url'));
        return Buffer.concat([decipher.update(Buffer.from(body, 'base64url')), decipher.final()]).toString('utf8');
      } catch {
        return undefined;
      }
    },
  };
}

/** Where ciphertexts are kept. Names are setting keys (`notify.url`, `smtp.pass` …). */
export interface SecretStore {
  /** every stored secret: name → ciphertext */
  all(): Promise<Record<string, string>>;
  put(name: string, ciphertext: string): Promise<void>;
  remove(name: string): Promise<void>;
}

export function memorySecretStore(initial: Record<string, string> = {}): SecretStore & { rows: Map<string, string> } {
  const rows = new Map(Object.entries(initial));
  return {
    rows,
    all: async () => Object.fromEntries(rows),
    put: async (name, ciphertext) => void rows.set(name, ciphertext),
    remove: async (name) => void rows.delete(name),
  };
}

/**
 * The file backend's store: one JSON file, mode 0600, beside the sign-in data
 * (`AUTH_DATA_DIR`, the `auth` volume) — outside the catalog directory, so the
 * git export and the catalog export never see it.
 */
export function fileSecretStore(path: string): SecretStore {
  const read = (): Record<string, string> => {
    if (!existsSync(path)) return {};
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as { secrets?: Record<string, string> };
    return { ...(parsed.secrets ?? {}) };
  };
  const write = (rows: Record<string, string>): void => {
    mkdirSync(dirname(path), { recursive: true });
    const sorted = Object.fromEntries(Object.entries(rows).sort(([a], [b]) => a.localeCompare(b)));
    // not `writeFileAtomic`: that one reports the path to the git export, and this file is never exported
    const temp = `${path}.${process.pid}.tmp`;
    writeFileSync(temp, `${JSON.stringify({ note: 'Secrets entered in WireHub Settings, encrypted with WIREHUB_SETTINGS_KEY. Not part of the catalog.', secrets: sorted }, null, 2)}\n`, { mode: 0o600 });
    chmodSync(temp, 0o600);
    renameSync(temp, path);
  };
  return {
    all: async () => read(),
    put: async (name, ciphertext) => write({ ...read(), [name]: ciphertext }),
    remove: async (name) => {
      const rows = read();
      if (!(name in rows)) return;
      delete rows[name];
      write(rows);
    },
  };
}
