/**
 * First-run setup: which domain modules this hub uses.
 *
 *   GET  /api/setup    the domain modules the build offers, which are enabled,
 *                      and whether setup still has to run
 *   POST /api/setup    { modules: string[] } — enable those modules: install
 *                      their catalog packs into the catalog, record the choice
 *
 * The WireHub base is generic; what a shop works on (video, automotive,
 * fieldbus …) arrives as **domain modules** (`docs/modules.md`), each with
 * a catalog pack. The build decides which domain modules are *available*
 * (`modules.config.ts`); a person decides which are *enabled*, here. Every
 * module starts unticked; a deployment may pre-tick some with
 * `WIREHUB_SUGGESTED_MODULES` (the config generator writes it), and the person
 * still decides. Enabling one installs its packs as layers in the **packs
 * directory** (`installPackLayer`, `@wirehub/catalog`: `/data/packs` in the
 * container, the gitignored `data/packs/` in a checkout) — never into the
 * starter catalog — and adds it to `setup.json` there, the stored selection.
 * Enabling is additive: a module is never uninstalled from here.
 *
 * Setup "has to run" when no completed `setup.json` exists and the host asked
 * for the prompt (`WIREHUB_SETUP_PROMPT=1`, set in the container image), so a
 * development checkout and the test suites never get bounced to /setup.
 *
 * **The setup code.** While setup has to run, a host that has a setup code
 * (`WIREHUB_SETUP_CODE`, generated by the compose stack's `bootstrap` service,
 * or made up at boot by `serve.ts`) prints it to its log and refuses a POST
 * without it, so a hub exposed by mistake cannot be set up by a stranger.
 */

import { randomInt, timingSafeEqual } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { isAbsolute, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { installPackLayer, readInstalledPacks, readPackManifest } from '@wirehub/catalog';
import type { ModuleRegistry, WireHubModule } from '@wirehub/modules';

import { writeFileAtomic } from './atomic-write.ts';
import type { ApiResponse } from './api.ts';

export interface SetupDeps {
  /** the catalog directory packs are checked against */
  dataDir: string;
  /**
   * where packs are installed and `setup.json` lives (`WIREHUB_PACKS_DIR`);
   * absent: the catalog directory itself (a host without a packs directory)
   */
  packsDir?: string;
  /** the one-time setup code a POST must carry while setup has to run; absent: none asked */
  code?: string;
  /** module ids to pre-tick (`WIREHUB_SUGGESTED_MODULES`); absent: each module's own `setup.suggested` */
  suggested?: readonly string[];
  /** run after packs were installed (the host regenerates derived tag tables) */
  afterInstall?: () => unknown;
  /** whether an unfinished setup should send the browser to /setup */
  prompt: boolean;
  /** now, ISO 8601 (injected by tests) */
  now: () => string;
  /**
   * A backend whose catalog is not a directory (Postgres): hands the handler
   * a directory holding the catalog and commits what the handler changed in
   * it as one change set (`pg/setup.ts`). Absent: `dataDir` is the catalog.
   */
  transact?: (run: (dataDir: string, packsDir: string) => Promise<ApiResponse>, write: boolean) => Promise<ApiResponse>;
}

/** `setup.json`: the stored selection. */
export interface SetupState {
  src: string;
  completed: boolean;
  completedAt?: string;
  completedBy?: string;
  /** enabled domain modules, in the order they were enabled */
  modules: string[];
}

/** A domain the setup page mentions that this build has no module for yet. */
export interface DomainSuggestion {
  label: string;
  description: string;
}

/**
 * Domains shown beside the bundled modules, so a person sees where WireHub
 * is going. Not installable: a domain moves from here to a real module once
 * one exists.
 */
export const DOMAIN_SUGGESTIONS: readonly DomainSuggestion[] = [
  { label: 'Fieldbus', description: 'PROFIBUS, CAN, Modbus, M8/M12 codings: planned (docs/catalog-store.md).' },
];

const SETUP_FILE = 'setup.json';
const SRC = 'the domain modules this hub uses, chosen at first-run setup (apps/studio/server/setup.ts)';

/** `setup.json` in `dir`, or `undefined` when there is none. */
export function readSetup(dir: string): SetupState | undefined {
  const path = join(dir, SETUP_FILE);
  return existsSync(path) ? (JSON.parse(readFileSync(path, 'utf8')) as SetupState) : undefined;
}

function writeSetup(dir: string, state: SetupState): void {
  mkdirSync(dir, { recursive: true });
  writeFileAtomic(join(dir, SETUP_FILE), `${JSON.stringify(state, null, 2)}\n`, 'utf8');
}

/** Where packs and `setup.json` go for these deps. */
export function packsDirOf(deps: SetupDeps): string {
  return deps.packsDir ?? deps.dataDir;
}

/**
 * The stored selection: the packs directory's `setup.json`, else one a hub
 * from before the packs directory left in its catalog directory.
 */
export function readSetupState(deps: SetupDeps): SetupState | undefined {
  return readSetup(packsDirOf(deps)) ?? (deps.packsDir === undefined ? undefined : readSetup(deps.dataDir));
}

/** Whether setup still has to run (the host asked for the prompt and no setup completed). */
export function setupNeeded(deps: SetupDeps): boolean {
  return deps.prompt && readSetupState(deps)?.completed !== true;
}

/** A setup code compared the forgiving way: case, spaces and dashes do not matter. */
export function normalizeSetupCode(code: string): string {
  return code.toUpperCase().replace(/[^A-Z0-9]/g, '');
}

function codeMatches(expected: string, given: unknown): boolean {
  if (typeof given !== 'string') return false;
  const a = Buffer.from(normalizeSetupCode(expected));
  const b = Buffer.from(normalizeSetupCode(given));
  return a.length > 0 && a.length === b.length && timingSafeEqual(a, b);
}

/** The setup code's alphabet: no 0/O, 1/I/L, so it reads back from a log without doubt. */
export const SETUP_CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

/** A fresh setup code, `XXXX-XXXX-XXXX` (about 59 bits). Host code only: it is random. */
export function generateSetupCode(): string {
  const chars = Array.from({ length: 12 }, () => SETUP_CODE_ALPHABET[randomInt(SETUP_CODE_ALPHABET.length)]);
  return [chars.slice(0, 4), chars.slice(4, 8), chars.slice(8)].map((group) => group.join('')).join('-');
}

/** The banner a host prints while setup has to run: where to go and the code to enter. */
export function setupBanner(url: string, code: string): string {
  const lines = ['WireHub first-run setup', '', `Open ${url}/setup and enter the setup code:`, '', `    ${code}`, '', 'It is asked once, until setup is finished.'];
  const width = Math.max(...lines.map((line) => line.length)) + 4;
  const rule = '='.repeat(width);
  return [rule, ...lines.map((line) => `  ${line}`), rule].join('\n');
}

/** `WIREHUB_SUGGESTED_MODULES`: comma- or space-separated module ids; `undefined` when unset or blank. */
export function parseSuggestedModules(value: string | undefined): string[] | undefined {
  if (value === undefined) return undefined;
  const ids = value.split(/[\s,]+/).filter((id) => id !== '');
  return ids.length === 0 ? undefined : ids;
}

/** A pack contribution's directory: a `file:` URL or an absolute path. */
export function packDirOf(root: string | undefined): string | undefined {
  if (root === undefined) return undefined;
  if (root.startsWith('file:')) return fileURLToPath(root);
  return isAbsolute(root) ? root : undefined;
}

function domainView(module: WireHubModule, enabled: readonly string[], installed: ReadonlySet<string>, suggested: readonly string[] | undefined): unknown {
  return {
    id: module.id,
    label: module.label,
    version: module.version,
    ...(module.license === undefined ? {} : { license: module.license }),
    description: module.setup?.description ?? '',
    suggested: suggested === undefined ? module.setup?.suggested === true : suggested.includes(module.id),
    enabled: enabled.includes(module.id),
    packs: (module.catalogPacks ?? []).map((pack) => ({
      id: pack.id,
      label: pack.label,
      version: pack.version,
      ...(pack.license === undefined ? {} : { license: pack.license }),
      installed: installed.has(pack.id),
    })),
  };
}

function view(deps: SetupDeps, modules: ModuleRegistry | undefined): unknown {
  const state = readSetupState(deps);
  const enabled = state?.modules ?? [];
  // packs installed as layers, plus any a hub from before merged into its catalog
  const installed = new Set([...readInstalledPacks(packsDirOf(deps)).packs, ...readInstalledPacks(deps.dataDir).packs].map((p) => p.id));
  const completed = state?.completed === true;
  return {
    needed: deps.prompt && !completed,
    completed,
    codeRequired: deps.code !== undefined && !completed,
    domains: (modules?.domains() ?? []).map((m) => domainView(m, enabled, installed, deps.suggested)),
    suggestions: DOMAIN_SUGGESTIONS,
  };
}

const json = (status: number, body: unknown): ApiResponse => ({ status, body });
const refuse = (status: number, error: string, hint?: string): ApiResponse => json(status, { error, ...(hint === undefined ? {} : { hint }) });

/** Is this a setup route? */
export function isSetupPath(path: string): boolean {
  return (path.split('?')[0] ?? '').replace(/\/+$/, '') === '/api/setup';
}

/**
 * `/api/setup`. The POST writes files directly (pack installs are journaled
 * by the installer), so the caller runs it under the write lock.
 */
export async function handleSetupRequest(
  request: { method: string; body?: unknown; user?: { name: string } },
  deps: SetupDeps | undefined,
  modules: ModuleRegistry | undefined,
): Promise<ApiResponse> {
  if (deps === undefined) return refuse(501, 'This host has no first-run setup.', 'Domain modules are installed by the deployment here.');
  if (deps.transact !== undefined) {
    const { transact, ...rest } = deps;
    return transact((dataDir, packsDir) => handleSetupRequest(request, { ...rest, dataDir, packsDir }, modules), request.method.toUpperCase() === 'POST');
  }
  const method = request.method.toUpperCase();
  if (method === 'GET') return json(200, view(deps, modules));
  if (method !== 'POST') return refuse(405, `${method} is not something this address accepts.`, 'It answers GET and POST.');

  const body = request.body as { modules?: unknown; code?: unknown } | undefined;
  if (deps.code !== undefined && readSetupState(deps)?.completed !== true && !codeMatches(deps.code, body?.code)) {
    return refuse(
      403,
      body?.code === undefined || body.code === '' ? 'Enter the setup code.' : 'That is not the setup code.',
      'The server prints it to its log at startup: `docker compose logs wirehub`, or the wirehub container\'s logs in your Docker UI.',
    );
  }
  const asked = body?.modules;
  if (!Array.isArray(asked) || !asked.every((id): id is string => typeof id === 'string')) {
    return refuse(400, 'Say which domain modules to enable.', 'Send { "modules": ["av-video", …] } — an empty list is fine.');
  }
  const domains = modules?.domains() ?? [];
  const unknown = asked.filter((id) => !domains.some((m) => m.id === id));
  if (unknown.length > 0) {
    return refuse(400, `Not a domain module of this build: ${unknown.join(', ')}.`, `This build offers ${domains.map((m) => m.id).join(', ') || 'none'}.`);
  }

  // check every pack before installing any, so a conflict leaves nothing half-done
  const chosen = domains.filter((m) => asked.includes(m.id));
  const plans: { module: string; pack: string; dir: string }[] = [];
  for (const module of chosen) {
    for (const pack of module.catalogPacks ?? []) {
      const dir = packDirOf(pack.root);
      if (dir === undefined) return refuse(500, `Module '${module.id}' names no directory for pack '${pack.id}'.`);
      try {
        readPackManifest(dir);
      } catch (error) {
        return refuse(500, error instanceof Error ? error.message : String(error));
      }
      plans.push({ module: module.id, pack: pack.id, dir });
    }
  }
  const installed: { module: string; pack: string; added: number; alreadyInstalled: boolean }[] = [];
  for (const plan of plans) {
    try {
      const result = installPackLayer(deps.dataDir, packsDirOf(deps), plan.dir);
      installed.push({
        module: plan.module,
        pack: plan.pack,
        added: Object.values(result.added).reduce((n, ids) => n + Math.max(1, ids.length), 0),
        alreadyInstalled: result.alreadyInstalled,
      });
    } catch (error) {
      return refuse(409, error instanceof Error ? error.message : String(error), 'Rename or remove the clashing record in the catalog, then run setup again.');
    }
  }

  if (installed.some((i) => !i.alreadyInstalled) && deps.afterInstall !== undefined) await deps.afterInstall();

  const before = readSetupState(deps);
  const modulesNow = [...(before?.modules ?? [])];
  for (const id of asked) if (!modulesNow.includes(id)) modulesNow.push(id);
  writeSetup(packsDirOf(deps), {
    src: SRC,
    completed: true,
    completedAt: before?.completedAt ?? deps.now(),
    ...(before?.completedBy !== undefined ? { completedBy: before.completedBy } : request.user === undefined ? {} : { completedBy: request.user.name }),
    modules: modulesNow,
  });
  return json(200, { ...(view(deps, modules) as object), installed });
}
