/**
 * Docs results for the command palette: the titles and headings of the docs site, from an index
 * shipped with the app (`docs-index.json`, generated by `node site/build.mjs docs-index`; a test
 * fails when it is stale). Nothing is fetched, so it works offline; only opening a result needs the
 * site (or a hub's own copy, `WIREHUB_DOCS_URL`). The index is a separate chunk, loaded when the
 * palette first opens.
 */

export interface DocsEntry {
  /** the page */
  title: string;
  /** the section; empty for the page itself */
  heading: string;
  /** relative to the docs base: `page/` or `page/#anchor` */
  path: string;
}

let loaded: Promise<readonly DocsEntry[]> | undefined;

export function loadDocsIndex(): Promise<readonly DocsEntry[]> {
  loaded ??= import('./docs-index.json').then((module) => module.default as readonly DocsEntry[]);
  return loaded;
}

/** Entries whose heading or page title contains every word of `query`, headings before pages, best first. */
export function searchDocs(index: readonly DocsEntry[], query: string, limit = 6): DocsEntry[] {
  const words = query.toLowerCase().split(/[^\p{L}\p{N}_]+/u).filter((word) => word !== '');
  if (words.length === 0) return [];
  const scored: { entry: DocsEntry; score: number }[] = [];
  for (const entry of index) {
    const heading = entry.heading.toLowerCase();
    const title = entry.title.toLowerCase();
    let score = 0;
    let all = true;
    for (const word of words) {
      const inHeading = heading.includes(word);
      const inTitle = title.includes(word);
      if (!inHeading && !inTitle) {
        all = false;
        break;
      }
      score += (inHeading ? 4 : 0) + (inTitle ? 2 : 0) + (heading.startsWith(word) ? 2 : 0);
    }
    if (all) scored.push({ entry, score: score + (entry.heading === '' ? 1 : 0) });
  }
  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((hit) => hit.entry);
}

/** The label a result shows: the section, with its page as the meta, or the page alone. */
export function docsEntryLabel(entry: DocsEntry): { label: string; meta: string } {
  return entry.heading === '' ? { label: entry.title, meta: 'docs' } : { label: entry.heading, meta: `docs · ${entry.title}` };
}
