#!/usr/bin/env python3
"""Regenerate src/frame/plex.generated.ts: the IBM Plex faces the sheets are set in.

    python3 fonts/gen-plex.py <@fontsource dir>     (needs: pip install fonttools brotli)

Reads the Latin woff2 subsets of @fontsource/ibm-plex-sans (400, 600) and
@fontsource/ibm-plex-mono (400, 500), keeps the woff2 bytes as base64 and
tabulates every glyph's advance width (1/1000 em) so layout code can measure
text without a font engine. IBM Plex is SIL OFL 1.1 (fonts/LICENSE-IBMPlex.txt).
"""
import base64, json, sys
from fontTools.ttLib import TTFont

root = sys.argv[1]
faces = [
    ('sans', 'IBM Plex Sans', 400, 'ibm-plex-sans/files/ibm-plex-sans-latin-400-normal.woff2'),
    ('sansSemi', 'IBM Plex Sans', 600, 'ibm-plex-sans/files/ibm-plex-sans-latin-600-normal.woff2'),
    ('mono', 'IBM Plex Mono', 400, 'ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2'),
    ('monoMedium', 'IBM Plex Mono', 500, 'ibm-plex-mono/files/ibm-plex-mono-latin-500-normal.woff2'),
]
out = [
    '/* eslint-disable */',
    '// GENERATED by fonts/gen-plex.py (woff2 as base64, advance widths) - do not edit by hand.',
    '// IBM Plex Sans and IBM Plex Mono: SIL OFL 1.1 (fonts/LICENSE-IBMPlex.txt).',
    '',
    'export interface PlexFace {',
    '  family: string;',
    '  weight: 400 | 500 | 600;',
    '  woff2: string;',
    '  /** advance widths, 1/1000 em */',
    '  widths: Readonly<Record<string, number>>;',
    '}',
    '',
]
for key, family, weight, path in faces:
    raw = open(f'{root}/{path}', 'rb').read()
    font = TTFont(f'{root}/{path}')
    upm = font['head'].unitsPerEm
    cmap = font.getBestCmap()
    widths = {chr(cp): round(font['hmtx'][name][0] * 1000 / upm) for cp, name in sorted(cmap.items()) if cp >= 0x20 and cp != 0x7f}
    out.append(f'export const {key}: PlexFace = {{ family: {json.dumps(family)}, weight: {weight}, woff2: {json.dumps(base64.b64encode(raw).decode())}, widths: {json.dumps(widths, ensure_ascii=False)} }};')
open('src/frame/plex.generated.ts', 'w').write('\n'.join(out) + '\n')
